#!/bin/python3

'''Q-1'''


import math
import os
import random
import re
import sys

# Complete the diagonalDifference function below.
def diagonalDifference(arr):
    summ=0
    summ1=0
    for i in range(0,len(arr)):
        summ+=arr[i][i]
        summ1+=arr[i][len(arr)-i-1]
    
    return(abs(summ-summ1));

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()




#!/bin/python3

'''Q-2'''


import math
import os
import random
import re
import sys

# Complete the extraLongFactorials function below.
def extraLongFactorials(n):
    fact=1
    for i in range(1,n+1):
        fact*=i
    print(fact)

if __name__ == '__main__':
    n = int(input())

    extraLongFactorials(n)
