#!/bin/python3

'''Q-1'''

import math
import os
import random
import re
import sys

# Complete the countingSort function below.
def countingSort(arr):
    print(max(arr))
    result=[0]*(max(arr)+1)
    print(len(result))
    for i in arr:
        result[i]+=1
    return(result)
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split())) 

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()



#!/bin/python3

'''Q-2'''


import math
import os
import random
import re
import sys

# Complete the countingSort function below.
def countingSort(arr):
    result=[0]*1000
    arr1=[]
    for i in arr:
        result[i]+=1
    for i in range(0,len(result)):
        for j in range(0,result[i]):
            arr1.append(i)
            print(i)
    return(arr1)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
