#!/bin/python3
'''Q-1'''
import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):
    if p>n/2:
        if n%2!=0:
            c=(n-p)/2
        else:
            c=(n-p+1)/2
    else:
        c=(p/2)
    return(int(c))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()

    
    
    #!/bin/python3

    '''Q-2'''
import math
import os
import random
import re
import sys

# Complete the migratoryBirds function below.
def migratoryBirds(ar):
    maxx=0
    a=[]
    for i in range(0,5):
        a.append(ar.count(i))
    for i in range(0,5):
        if a[i]>maxx:
            maxx=a[i]
            pos=i
        
    return (pos)
        
            
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = migratoryBirds(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
