#!/bin/python3
'''Q-1'''
import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):
    if p>n/2:
        if n%2!=0:
            c=(n-p)/2
        else:
            c=(n-p+1)/2
    else:
        c=(p/2)
    return(int(c))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
