#!/bin/python3
'''Q-1'''
import math
import os
import random
import re
import sys

# Complete the bonAppetit function below.
def bonAppetit(bill, k, b):
    summ=sum(bill[0:k])+sum(bill[k+1:])
    fin=summ/2
    if fin==b:
        print("Bon Appetit")
    else:
        print(abs(int(fin-b)))

if __name__ == '__main__':
    nk = input().rstrip().split()

    n = int(nk[0])

    k = int(nk[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
    
    
    
    
    
    #!/bin/python3
    '''Q-2'''

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    flag=0
    if (x1>x2 and v1>v2) or (x1<x2 and v1<v2):
        return("NO")
    else:
        for i in range(0,100000):
            x1+=v1;
            x2+=v2;
            if x1==x2:
                flag=1
                return("YES")
        if flag==0:
            return("NO")
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(str(result))

    fptr.close()

